
	enum class JecUncertEnum {
	AbsoluteStat = 0, 
	AbsoluteScale = 1, 
	AbsoluteMPFBias = 2, 
	Fragmentation = 3, 
	SinglePionECAL = 4, 
	SinglePionHCAL = 5, 
	FlavorQCD = 6, 
	TimePtEta = 7, 
	RelativeJEREC1 = 8, 
	RelativeJEREC2 = 9, 
	RelativeJERHF = 10, 
	RelativePtBB = 11, 
	RelativePtEC1 = 12, 
	RelativePtEC2 = 13, 
	RelativePtHF = 14, 
	RelativeBal = 15, 
	RelativeFSR = 16, 
	RelativeStatFSR = 17, 
	RelativeStatEC = 18, 
	RelativeStatHF = 19, 
	PileUpDataMC = 20, 
	PileUpPtRef = 21, 
	PileUpPtBB = 22, 
	PileUpPtEC1 = 23, 
	PileUpPtEC2 = 24, 
	PileUpPtHF = 25, 
	Total = 26, 
	NONE = 27
	};

	const vector<string> JecUncertNames =
	{
	"AbsoluteStat",
	"AbsoluteScale",
	"AbsoluteMPFBias",
	"Fragmentation",
	"SinglePionECAL",
	"SinglePionHCAL",
	"FlavorQCD",
	"TimePtEta",
	"RelativeJEREC1",
	"RelativeJEREC2",
	"RelativeJERHF",
	"RelativePtBB",
	"RelativePtEC1",
	"RelativePtEC2",
	"RelativePtHF",
	"RelativeBal",
	"RelativeFSR",
	"RelativeStatFSR",
	"RelativeStatEC",
	"RelativeStatHF",
	"PileUpDataMC",
	"PileUpPtRef",
	"PileUpPtBB",
	"PileUpPtEC1",
	"PileUpPtEC2",
	"PileUpPtHF",
	"Total",
	""
	};
